services:
  - type: web
    name: spotify-cover-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn spotify:app --host 0.0.0.0 --port $PORT"
    plan: free
    autoDeploy: true
